source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CircularScrollView_Example', :exclusive => true do
  pod "CircularScrollView", :path => "../"
end

target 'CircularScrollView_Tests', :exclusive => true do
  pod "CircularScrollView", :path => "../"

  pod 'FBSnapshotTestCase'
end
